package net.asg.games.utils.enums;

public enum ServerRequest {
    REQUEST_ALL_DEBUG_PLAYERS,
    REQUEST_LOGIN,
    REQUEST_LOGOFF,
    REQUEST_PLAYER_REGISTER,
    REQUEST_CREATE_GAME,
    REQUEST_PLAY_GAME,
    REQUEST_TABLE_STAND,
    REQUEST_TABLE_JOIN,
    REQUEST_TABLE_SIT,
    REQUEST_ROOM,
    REQUEST_ROOM_JOIN,
    REQUEST_ROOM_LEAVE,
    REQUEST_LOUNGE,
    REQUEST_TABLE_INFO,
    REQUEST_LOUNGE_ALL
}